import { writeFileSync, readFileSync, mkdirSync, existsSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import type { Skeleton, SkeletonState, GuardedTransition } from "./schema.js";
import { parseSkeletonXML } from "./xml.js";
import { compileGuardExpr } from "./expr.js";
import { stateRoleMap, computeRoles, visibleProducers } from "./analysis/graph.js";

/** Producers visible to a node, split by how the runtime exposes them (single dir vs per-branch list). */
type Visible = { single: string[]; list: string[] };
import { ensureESMPackage, reconcile } from "./project-fs.js";

/** Compile every skeleton in `.reharness/skeletons/`, then reconcile orphan files. */
export function generateAllFromSkeletons(reharnessDir: string): void {
  const skeletonsDir = resolve(reharnessDir, "skeletons");
  if (!existsSync(skeletonsDir)) return;

  const skeletons: Skeleton[] = [];
  for (const file of readdirSync(skeletonsDir).filter(f => f.endsWith(".xml"))) {
    try {
      const sk = parseSkeletonXML(readFileSync(resolve(skeletonsDir, file), "utf-8"));
      generateFromSkeleton(sk, reharnessDir);
      skeletons.push(sk);
    } catch { /* invalid XML — skip */ }
  }
  reconcile(reharnessDir, skeletons);
}

/** Deterministic: skeleton.xml → commands/<id>.ts + lib/<id>-states.ts + agents/<name>.md stubs. */
export function generateFromSkeleton(sk: Skeleton, reharnessDir: string): void {
  const commandPath = resolve(reharnessDir, "commands", `${sk.id}.ts`);
  const libPath = resolve(reharnessDir, "lib", `${sk.id}-states.ts`);
  const agentsDir = resolve(reharnessDir, "agents");

  ensureESMPackage(resolve(reharnessDir, ".."), sk.id);
  mkdirSync(dirname(commandPath), { recursive: true });
  mkdirSync(dirname(libPath), { recursive: true });
  mkdirSync(agentsDir, { recursive: true });

  const codeStates = Object.keys(sk.states).filter(n => sk.states[n].type === "code");
  const agentStates = Object.keys(sk.states).filter(n => {
    const t = sk.states[n].type;
    return t === "agent" || t === "interactive";
  });

  writeFileSync(commandPath, emitCommand(sk, codeStates));

  if (!existsSync(libPath)) {
    writeFileSync(libPath, emitLib(sk, codeStates));
  } else {
    let existing = readFileSync(libPath, "utf-8");
    // (1) Update return-type annotation of existing entry functions whose declared events changed.
    for (const n of codeStates) {
      if (!existing.includes(`function ${n}Entry`)) continue;
      const events = Object.keys(sk.states[n].on || {});
      existing = updateSignature(existing, n, events);
    }
    // (2) Append stubs for new code states that don't have an entry function yet.
    const newStubs = codeStates
      .filter(n => !existing.includes(`function ${n}Entry`))
      .map(n => stubFn(n, sk.states[n], visibleProducers(sk, n, computeRoles(sk))))
      .join("\n");
    const updated = newStubs ? existing + "\n" + newStubs : existing;
    writeFileSync(libPath, updated);
  }

  for (const name of agentStates) {
    const p = resolve(agentsDir, `${name}.md`);
    if (!existsSync(p)) writeFileSync(p, `<!-- TODO: prompt for ${name} -->\n`);
  }

  emitCompiled(sk, reharnessDir);
}

/** Re-emit the consolidated single-file view after lib/agents bodies have been filled.
 *  Call this from /generate's review state so the review agent sees the current state. */
export function emitCompiledFromSkeletonsDir(reharnessDir: string): void {
  const skeletonsDir = resolve(reharnessDir, "skeletons");
  if (!existsSync(skeletonsDir)) return;
  for (const file of readdirSync(skeletonsDir).filter(f => f.endsWith(".xml"))) {
    try {
      const sk = parseSkeletonXML(readFileSync(resolve(skeletonsDir, file), "utf-8"));
      emitCompiled(sk, reharnessDir);
    } catch { /* skip invalid */ }
  }
}

/** Single-file consolidated view of the entire pipeline (skeleton + lib + agents).
 *  The skeleton XML embeds the topology + per-node contracts, so it is the single source of truth.
 *  Used by the `review` agent so it reads one file instead of 17+. */
function emitCompiled(sk: Skeleton, reharnessDir: string): void {
  const genDir = resolve(reharnessDir, "generate");
  if (!existsSync(genDir)) return; // codegen called outside /generate flow
  const compiledPath = resolve(genDir, "_compiled.md");
  const skeletonPath = resolve(reharnessDir, "skeletons", `${sk.id}.xml`);
  const libPath = resolve(reharnessDir, "lib", `${sk.id}-states.ts`);
  const agentsDir = resolve(reharnessDir, "agents");

  const parts: string[] = [];
  parts.push(`# Compiled Pipeline: ${sk.id}\n`);
  parts.push(`> Auto-generated by codegen. Single-file view of the entire pipeline for the review agent — read this file instead of opening skeleton + lib + every agent prompt separately. The skeleton XML embeds the topology and per-node contracts.\n`);

  if (existsSync(skeletonPath)) {
    parts.push(`## Skeleton XML (topology + contracts)\n`);
    parts.push("```xml\n" + readFileSync(skeletonPath, "utf-8").trimEnd() + "\n```\n");
  }

  parts.push(`## Agent Prompts\n`);
  for (const [name, state] of Object.entries(sk.states)) {
    if (state.type !== "agent" && state.type !== "interactive") continue;
    const p = resolve(agentsDir, `${name}.md`);
    if (!existsSync(p)) continue;
    parts.push(`### \`${name}\` (${state.type})\n`);
    parts.push("```markdown\n" + readFileSync(p, "utf-8").trimEnd() + "\n```\n");
  }

  if (existsSync(libPath)) {
    parts.push(`## Code States (lib/${sk.id}-states.ts)\n`);
    parts.push("```typescript\n" + readFileSync(libPath, "utf-8").trimEnd() + "\n```\n");
  }

  writeFileSync(compiledPath, parts.join("\n"));
}

export function emitCommand(sk: Skeleton, codeStates: string[]): string {
  const importsLib = codeStates.length
    ? `\nimport { ${codeStates.map(s => `${s}Entry`).join(", ")} } from '../lib/${sk.id}-states.js';`
    : "";

  const calledSkeletons = Array.from(new Set(
    Object.values(sk.states)
      .filter((s): s is SkeletonState & { callSkeleton: string } => s.type === "call" && !!s.callSkeleton)
      .map(s => s.callSkeleton),
  ));
  const importsCalls = calledSkeletons
    .map(id => `import subCmd_${sanitizeId(id)} from './${id}.js';`)
    .join("\n");

  const roles = stateRoleMap(sk);
  // Data inputs are DERIVED from the graph, not declared: each node sees its ancestor producers (single dir,
  // or one dir per branch for parallel-branch producers). The runtime resolves these and injects them.
  const roleMaps = computeRoles(sk);
  const stateBlocks = Object.entries(sk.states)
    .map(([n, s]) => emitState(n, s, roles.get(n), visibleProducers(sk, n, roleMaps)))
    .join("\n");
  return `import { defineCommand, definePipeline } from 'reharness';
import { resolve } from 'path';${importsLib}${importsCalls ? "\n" + importsCalls : ""}

export default defineCommand({
  description: ${JSON.stringify(sk.description)},
  usage: ${JSON.stringify(sk.usage || '<args...>')},

${emitRun(sk, stateBlocks)}
});
`;
}

/** Generate the command's `run()`. The CLI→config wiring is DERIVED from the declared `<inputs>` (the external
 *  interface), so config carries exactly the fields the pipeline reads — correct by construction. With no
 *  `<inputs>`, only `config.{target,input}` are provided (the generator convention: input → slug → target dir). */
function emitRun(sk: Skeleton, stateBlocks: string): string {
  const slugExpr = `input.replace(/[^a-zA-Z0-9\\u0400-\\u04FF]+/g, '-').replace(/^-|-$/g, '').slice(0, 80) || ${JSON.stringify(sk.id)}`;
  const pipeline = `    return definePipeline({
      config,
      agents: ctx.agents,
      cwd: target,
      logsDir: resolve(target, 'logs'),
      initial: ${JSON.stringify(sk.initial)},
      states: {
${stateBlocks}
      },
    });`;

  if (!sk.inputs?.length) {
    return `  run: (args, ctx) => {
    const input = args.join(' ');
    const slug = ${slugExpr};
    const target = resolve(ctx.cwd, slug);
    const config = { target, input };
${pipeline}
  },`;
  }

  let pos = 0;
  const assigns = sk.inputs.map(d => {
    const src = d.positional
      ? `positional[${pos++}]`
      : `flags[${JSON.stringify((d.flag ?? `--${d.name.replace(/_/g, "-")}`).replace(/^--/, ""))}]`;
    const coerce = (e: string) => d.type === "list" ? `String(${e}).split(',').map(s => s.trim()).filter(Boolean)`
      : d.type === "number" ? `Number(${e})`
      : d.type === "bool" ? `(${e} === true || ${e} === 'true')`
      : `String(${e})`;
    const dflt = d.default !== undefined ? coerce(JSON.stringify(d.default))
      : d.type === "list" ? "[]" : d.type === "bool" ? "false" : "undefined";
    const guard = d.required ? `if (${src} === undefined) return null; ` : "";
    return `    ${guard}config[${JSON.stringify(d.name)}] = ${src} === undefined ? ${dflt} : ${coerce(src)};`;
  });

  return `  run: (args, ctx) => {
    const flags: Record<string, any> = {}; const positional: string[] = [];
    for (let i = 0; i < args.length; i++) {
      const a = args[i];
      if (a.startsWith('--')) { const eq = a.indexOf('='); if (eq >= 0) flags[a.slice(2, eq)] = a.slice(eq + 1); else if (i + 1 < args.length && !args[i + 1].startsWith('--')) flags[a.slice(2)] = args[++i]; else flags[a.slice(2)] = true; }
      else positional.push(a);
    }
    const input = positional.join(' ');
    const slug = ${slugExpr};
    const target = resolve(ctx.cwd, slug);
    const config: Record<string, any> = { target, input };
${assigns.join("\n")}
${pipeline}
  },`;
}

function emitState(name: string, state: SkeletonState, role?: "branch" | "join" | "step", vis: Visible = { single: [], list: [] }): string {
  const block = emitStateBody(name, state, role, vis);
  if (!state.timeout) return block;
  // Inject ` timeoutMs: N` just before the closing `},`. Match an optional preceding comma so we don't
  // duplicate it when the inner content already ends with one (multi-line templates do).
  return block.replace(/,?\s*\}\s*,\s*$/, `${timeoutField(state)} },`);
}

function emitStateBody(name: string, state: SkeletonState, role?: "branch" | "join" | "step", vis: Visible = { single: [], list: [] }): string {
  if (state.type === "final") {
    return `        ${name}: { type: 'final', status: '${state.status || "success"}' },`;
  }
  if (state.type === "approval") {
    const parts = [
      `type: 'approval'`,
      `prompt: ${JSON.stringify(state.prompt || "")}`,
      ...(state.artifacts?.length ? [`artifacts: ${JSON.stringify(state.artifacts)}`] : []),
      ...(state.autoEvent ? [`autoEvent: ${JSON.stringify(state.autoEvent)}`] : []),
      `on: ${emitTransitions(state.on || {})}`,
    ];
    return `        ${name}: { ${parts.join(", ")} },`;
  }
  if (state.type === "switch") {
    const branches = (state.branches || []).map(emitBranch).join(", ");
    return `        ${name}: { type: 'switch', branches: [${branches}] },`;
  }
  if (state.type === "parallel") {
    const overBody = compileGuardExpr(state.overExpr || "[]");
    const conc = state.concurrency !== undefined ? `, concurrency: ${state.concurrency}` : "";
    const onPart = state.on && Object.keys(state.on).length ? `, on: ${emitTransitions(state.on)}` : "";
    return `        ${name}: { type: 'parallel', over: (c) => (${overBody}), branch: '${state.parallelBranch}', join: '${state.join}'${conc}${onPart} },`;
  }
  if (state.type === "loop") {
    const stepsJson = JSON.stringify(state.loopSteps || []);
    const maxPart = state.maxIterations !== undefined ? `, max: ${state.maxIterations}` : "";
    const exitPart = state.exitExpr ? `, exit: (c) => (${compileGuardExpr(state.exitExpr)})` : "";
    const onPart = state.on && Object.keys(state.on).length ? `, on: ${emitTransitions(state.on)}` : "";
    return `        ${name}: { type: 'loop', steps: ${stepsJson}, join: '${state.join}'${maxPart}${exitPart}${onPart} },`;
  }
  if (state.type === "wait") {
    const parts: string[] = [`type: 'wait'`, `mode: ${JSON.stringify(state.waitMode)}`];
    if (state.waitDuration) parts.push(`durationMs: ${parseDurationMs(state.waitDuration)}`);
    if (state.waitTimeout) parts.push(`timeoutMs: ${parseDurationMs(state.waitTimeout)}`);
    if (state.waitPath) parts.push(`path: ${JSON.stringify(state.waitPath)}`);
    if (state.waitCommand) parts.push(`command: ${JSON.stringify(state.waitCommand)}`);
    if (state.waitPort !== undefined) parts.push(`port: ${state.waitPort}`);
    if (state.waitPollInterval) parts.push(`pollIntervalMs: ${parseDurationMs(state.waitPollInterval)}`);
    parts.push(`on: ${emitTransitions(state.on || {})}`);
    return `        ${name}: { ${parts.join(", ")} },`;
  }
  if (state.type === "call") {
    const subId = state.callSkeleton!;
    const argsBody = state.callArgsExpr ? compileGuardExpr(state.callArgsExpr) : "[]";
    const onObj = emitTransitions(state.on || {});
    return `        ${name}: {
          type: 'call',
          skeleton: ${JSON.stringify(subId)},
          argsFn: (c) => (${argsBody}),
          callFactory: (callArgs) => subCmd_${sanitizeId(subId)}.run(callArgs, ctx),
          on: ${onObj},
        },`;
  }
  if (state.type === "set") {
    const assignments = (state.dataAssignments || [])
      .map(a => `            c.data[${JSON.stringify(a.key)}] = ${compileGuardExpr(a.value)};`)
      .join("\n");
    return `        ${name}: {
          entry: async (c) => {
${assignments}
            return 'DONE';
          },
          on: ${emitTransitions(state.on || { DONE: "" })},
        },`;
  }

  const on = { ...(state.on || {}) };
  if (state.type === "code" && !on["ERROR"]) on["ERROR"] = "error";

  if (state.type === "agent") {
    const optsExpr = agentOpts(state, role, vis);
    if (role === "branch") {
      return `        ${name}: {
          entry: async (c) => {
            const task = [
              \`Execute the ${name} stage (parallel branch \${c.branchIndex}).\`,
              \`Working directory: \${c.config.target}\`,
              \`Branch input: \${JSON.stringify(c.branchInput)}\`,
            ].join('\\n');
            await c.agent('${name}', task, ${optsExpr});
          },
          on: ${emitTransitions(on)},
        },`;
    }
    if (role === "join") {
      return `        ${name}: {
          entry: async (c) => {
            const task = [
              \`Execute the ${name} stage (joining branches/iterations).\`,
              \`Working directory: \${c.config.target}\`,
              \`Input: \${c.config.input}\`,
              c.data.branches !== undefined ? \`Branches: \${JSON.stringify(c.data.branches)}\` : '',
              c.data.iterations !== undefined ? \`Iterations completed: \${c.data.iterations}\` : '',
            ].filter(Boolean).join('\\n');
            await c.agent('${name}', task, ${optsExpr});
          },
          on: ${emitTransitions(on)},
        },`;
    }
    if (role === "step") {
      return `        ${name}: {
          entry: async (c) => {
            const task = [
              \`Execute the ${name} stage (loop step, iteration \${c.data.iteration}).\`,
              \`Working directory: \${c.config.target}\`,
              \`Input: \${c.config.input}\`,
            ].join('\\n');
            await c.agent('${name}', task, ${optsExpr});
          },
          on: ${emitTransitions(on)},
        },`;
    }
    return `        ${name}: {
          entry: async (c) => { await c.agent('${name}', \`Execute the ${name} stage.\\nWorking directory: \${c.config.target}\\nInput: \${c.config.input}\`, ${optsExpr}); },
          on: ${emitTransitions(on)},
        },`;
  }

  if (state.type === "interactive") {
    const artifacts = state.artifacts || [];
    const artifactsJson = JSON.stringify(artifacts);
    const fileList = artifacts.map(a => `  - ${a}`).join("\\n");
    return `        ${name}: {
          entry: async (c) => {
            const artifacts = ${artifactsJson};
            const task = [
              \`Execute the ${name} stage (interactive).\`,
              \`Working directory: \${c.config.target}\`,
              \`Input: \${c.config.input}\`,
              '',
              'CONTRACT — you MUST follow:',
              '- Edit ONLY these files:\\n${fileList}',
              '- Do not create, rename, or delete other files.',
              '- Do not modify files outside the working directory.',
              '- When done, exit the Pi session (Ctrl+D or /quit).',
            ].join('\\n');
            await c.interactive('${name}', task, { artifacts });
          },
          on: ${emitTransitions(on)},
        },`;
  }

  // code state
  const retryIncrements = retryKeysOf(on)
    .map(({ event, key }) => `              if (event === '${event}') c.retry('${key}');`)
    .join("\n");
  return `        ${name}: {
          entry: async (c) => {
            try {
              const event = ${name}Entry(c);
${retryIncrements ? retryIncrements + "\n" : ""}              return event;
            } catch (err: any) {
              c.emit(\`✗ ${name}: \${err.message}\`);
              return 'ERROR';
            }
          },
          on: ${emitTransitions(on)},
        },`;
}

function emitTransitions(on: Record<string, string | GuardedTransition[]>): string {
  const entries = Object.entries(on);
  if (entries.length === 1 && entries[0][0] === "DONE" && typeof entries[0][1] === "string") {
    return `'${entries[0][1]}'`;
  }
  const parts = entries.map(([event, target]) => {
    if (typeof target === "string") return `${event}: '${target}'`;
    return `${event}: [${target.map(emitBranch).join(", ")}]`;
  });
  return `{ ${parts.join(", ")} }`;
}

function emitBranch(gt: GuardedTransition): string {
  if (!gt.guard) return `{ target: '${gt.target}' }`;
  const retry = gt.guard.match(/^retries:(\w+)<(\d+)$/);
  if (retry) return `{ target: '${gt.target}', guard: (c) => c.retries('${retry[1]}') < ${retry[2]} }`;
  if (gt.guard.startsWith("expr:")) {
    const body = compileGuardExpr(gt.guard.slice(5));
    return `{ target: '${gt.target}', guard: (c) => (${body}) }`;
  }
  return `{ target: '${gt.target}' }`;
}

function retryKeysOf(on: Record<string, string | GuardedTransition[]>): Array<{ event: string; key: string }> {
  const out: Array<{ event: string; key: string }> = [];
  // At most ONE retry increment per event: the entry function fires `c.retry(key)` once when the event occurs.
  // If an event has several retry-guarded branches, they share the same counter intent — emitting one c.retry
  // per branch would multiply-increment on a single occurrence. Keep the first key seen for each event.
  for (const [event, target] of Object.entries(on)) {
    if (!Array.isArray(target)) continue;
    const gt = target.find(g => /^retries:(\w+)<(\d+)$/.test(g.guard ?? ""));
    const m = gt?.guard?.match(/^retries:(\w+)<(\d+)$/);
    if (m) out.push({ event, key: m[1] });
  }
  return out;
}

function returnUnion(events: string[]): string {
  return events.length ? events.map(e => `'${e}'`).join(" | ") : "'DONE'";
}

function stubFn(name: string, state: SkeletonState, vis: Visible = { single: [], list: [] }): string {
  const events = Object.keys(state.on || {});
  const union = returnUnion(events);
  // The runtime owns all paths — never build one by hand. Write this state's own output files into c.out();
  // read a single upstream producer's files from c.dir('<stage>'); read a parallel-branch producer's per-item
  // dirs from c.dirs('<stage>'). ctx.data carries scalar values to guards.
  const hints = [
    ...vis.single.map(p => `  //   - readFileSync(join(c.dir('${p}'), '<file>'))`),
    ...vis.list.map(p => `  //   - for (const d of c.dirs('${p}')) readFileSync(join(d, '<file>'))  // one dir per branch`),
  ];
  const inputsHint = hints.length ? `  // Upstream outputs available to read:\n${hints.join("\n")}\n` : "";
  return `export function ${name}Entry(c: any): ${union} {
  // TODO: implement ${name} — write outputs into c.out()
${inputsHint}  // Returns only events declared by the skeleton's <on>: ${union}.
  // Do not invent additional return values — let exceptions throw (codegen wraps them as ERROR).
  return '${events[0] || "DONE"}';
}
`;
}

/** Rewrite the return type annotation of `function <name>Entry(...): TYPE` to the new union. Preserves body. */
function updateSignature(source: string, name: string, events: string[]): string {
  const union = returnUnion(events);
  const re = new RegExp(
    `(export function ${name}Entry\\s*\\([^)]*\\)\\s*:\\s*)[^{\\n]+?(\\s*\\{)`,
    "m",
  );
  return source.replace(re, `$1${union}$2`);
}

function sanitizeId(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, "_");
}

/** Build the `opts` argument for an agent state's c.agent(name, task, OPTS) call.
 *  Merges dynamic model routing (modelExpr > parallel-branch input) with the visible producers — single-dir
 *  (`inputs`) and per-branch (`inputLists`) — that the runtime exposes to this agent. All DERIVED from the
 *  topology (visibleProducers), never declared, so producer and consumer can't drift. */
function agentOpts(state: SkeletonState, role: "branch" | "join" | "step" | undefined, vis: Visible): string {
  const dataEntries: string[] = [];
  if (vis.single.length) dataEntries.push(`inputs: ${JSON.stringify(vis.single)}`);
  if (vis.list.length) dataEntries.push(`inputLists: ${JSON.stringify(vis.list)}`);

  // Per-leaf harness (synthesized from <harness>). thinking / context-files are static; model from the
  // harness is the fallback BELOW dynamic model sources (precedence: model-expr > branch input > harness > default).
  const h = state.harness;
  if (h?.thinking) dataEntries.push(`thinking: ${JSON.stringify(h.thinking)}`);
  if (h?.contextFiles === false) dataEntries.push(`noContextFiles: true`);

  const dynModel = state.modelExpr
    ? compileGuardExpr(state.modelExpr)
    : role === "branch"
      ? `((c.branchInput && typeof c.branchInput === 'object') ? c.branchInput.model : undefined)`
      : null;
  // Static harness model becomes the fallback when no dynamic model resolves.
  const modelSrc = dynModel && h?.model
    ? `(${dynModel} ?? ${JSON.stringify(h.model)})`
    : dynModel ?? (h?.model ? JSON.stringify(h.model) : null);

  if (!dataEntries.length && !modelSrc) return "undefined";

  // IIFE so the dynamic model and the derived inputs merge cleanly into one opts object.
  const entries = ["...(m ? { model: m } : {})", ...dataEntries];
  return `(((m) => ({ ${entries.join(", ")} }))(${modelSrc ?? "undefined"}))`;
}

function timeoutField(state: SkeletonState): string {
  return state.timeout ? `, timeoutMs: ${parseDurationMs(state.timeout)}` : "";
}

function parseDurationMs(s: string): number {
  const m = s.match(/^(\d+)\s*(ms|s|m|h)$/);
  if (!m) throw new Error(`Invalid duration: '${s}'`);
  const n = parseInt(m[1], 10);
  return m[2] === "ms" ? n : m[2] === "s" ? n * 1000 : m[2] === "m" ? n * 60_000 : n * 3_600_000;
}

function emitLib(sk: Skeleton, codeStates: string[]): string {
  const roleMaps = computeRoles(sk);
  const fns = codeStates.map(n => stubFn(n, sk.states[n], visibleProducers(sk, n, roleMaps))).join("\n");
  return `// Code-state entry functions for ${sk.id}. Each returns an event string.\n\n${fns}`;
}

